import { useEffect, useState } from "react";
import { actOnAnalysisTemplate, createAdminAnalysisTemplate, listAdminAnalysisTemplates, updateAdminAnalysisTemplate } from "../../lib/api";
import type { AnalysisTemplate } from "../../types";

const empty = { slug: "", name: "", scenario: "", systemPrompt: "", checklist: [] as string[], requiredSkills: [] as string[], outputFormat: "", requiredEvidenceFields: [] as string[], recommendedModel: "chatgpt-5.4-az", organizationId: null as number | null };

export function AdminAnalysisTemplatesPanel() {
  const [items, setItems] = useState<AnalysisTemplate[]>([]); const [editing, setEditing] = useState<AnalysisTemplate | null>(null);
  const [draft, setDraft] = useState(empty); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = () => listAdminAnalysisTemplates().then(result => setItems(result.items)).catch(error => setError(error instanceof Error ? error.message : "模板加载失败"));
  useEffect(() => { void load(); }, []);
  function select(item: AnalysisTemplate | null) { setEditing(item); setDraft(item ? { slug:item.slug,name:item.name,scenario:item.scenario,systemPrompt:item.systemPrompt,checklist:item.checklist,requiredSkills:item.requiredSkills,outputFormat:item.outputFormat,requiredEvidenceFields:item.requiredEvidenceFields,recommendedModel:item.recommendedModel,organizationId:item.organizationId } : empty); }
  async function save() { setBusy(true); setError(null); try { if (editing) await updateAdminAnalysisTemplate(editing.id, draft); else await createAdminAnalysisTemplate(draft); select(null); await load(); } catch (error) { setError(error instanceof Error ? error.message : "保存失败"); } finally { setBusy(false); } }
  async function action(item: AnalysisTemplate, value: "publish"|"disable"|"copy") { setBusy(true); try { await actOnAnalysisTemplate(item.id,value); await load(); } finally { setBusy(false); } }
  return <section className="admin-card admin-card--wide"><p className="eyebrow">安全分析</p><h2>分析模板</h2><p className="admin-card__copy">管理模板内容、发布状态、组织可见性和版本快照。</p>{error ? <p role="alert">{error}</p> : null}
    <div className="template-admin"><div>{items.map(item => <article key={item.id} className="admin-card"><small>{item.status} · v{item.version} · {item.organizationId ? `组织 ${item.organizationId}` : "全局"}</small><h3>{item.name}</h3><p>{item.scenario}</p><button onClick={()=>select(item)}>编辑</button> <button disabled={busy} onClick={()=>void action(item,item.status === "published" ? "disable" : "publish")}>{item.status === "published" ? "停用" : "发布"}</button> <button disabled={busy} onClick={()=>void action(item,"copy")}>复制</button></article>)}</div>
    <form onSubmit={event=>{event.preventDefault();void save();}}><h3>{editing ? `编辑 ${editing.name}` : "创建模板"}</h3><input required placeholder="名称" value={draft.name} onChange={e=>setDraft(v=>({...v,name:e.target.value}))}/><input placeholder="Slug" value={draft.slug} onChange={e=>setDraft(v=>({...v,slug:e.target.value}))}/><textarea required placeholder="适用场景" value={draft.scenario} onChange={e=>setDraft(v=>({...v,scenario:e.target.value}))}/><textarea required placeholder="系统提示词" value={draft.systemPrompt} onChange={e=>setDraft(v=>({...v,systemPrompt:e.target.value}))}/><textarea required placeholder="检查清单（每行一项）" value={draft.checklist.join("\n")} onChange={e=>setDraft(v=>({...v,checklist:e.target.value.split("\n").filter(Boolean)}))}/><input placeholder="所需 Skill（逗号分隔）" value={draft.requiredSkills.join(",")} onChange={e=>setDraft(v=>({...v,requiredSkills:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)}))}/><textarea required placeholder="输出格式" value={draft.outputFormat} onChange={e=>setDraft(v=>({...v,outputFormat:e.target.value}))}/><input required placeholder="必填证据字段（逗号分隔）" value={draft.requiredEvidenceFields.join(",")} onChange={e=>setDraft(v=>({...v,requiredEvidenceFields:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)}))}/><input required placeholder="推荐模型" value={draft.recommendedModel} onChange={e=>setDraft(v=>({...v,recommendedModel:e.target.value}))}/><input type="number" placeholder="组织 ID（留空为全局）" value={draft.organizationId ?? ""} onChange={e=>setDraft(v=>({...v,organizationId:e.target.value ? Number(e.target.value) : null}))}/><button disabled={busy} type="submit">{busy ? "保存中…" : "保存新版本"}</button>{editing ? <button type="button" onClick={()=>select(null)}>取消</button> : null}</form></div>
  </section>;
}
