from __future__ import annotations

import json
import hashlib
import re
import uuid
from datetime import datetime, timezone
from typing import Any

import httpx

from fastapi import HTTPException
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import SkillPackage, SkillRun
from app.config import settings
from app.models import CaseIndicator, CaseEvent, InvestigationCase


def _safe_identifier(value: str, prefix: str = "cipher_rule") -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", value.strip())
    normalized = re.sub(r"_+", "_", normalized).strip("_")
    if not normalized: normalized = prefix
    if normalized[0].isdigit(): normalized = f"{prefix}_{normalized}"
    return normalized[:80]


def _string_list(value: Any, *, limit: int = 100) -> list[str]:
    if not isinstance(value, list):
        raise HTTPException(status_code=422, detail="Skill 输入必须是数组")
    return [str(item).strip() for item in value[:limit] if str(item).strip()]


def _build_sigma(payload: dict[str, Any]) -> dict[str, Any]:
    indicators = _string_list(payload.get("indicators"))
    if not indicators: raise HTTPException(status_code=422, detail="至少需要一个检测指标")
    title = str(payload.get("title", "Cipher IOC detection")).strip()[:160]
    logsource = str(payload.get("logsource", "proxy")).strip()[:40]
    rule_id = str(uuid.uuid5(uuid.NAMESPACE_URL, f"cipher:sigma:{title}:{'|'.join(indicators)}"))
    quoted = "\n".join(f"      - {json.dumps(value, ensure_ascii=False)}" for value in indicators)
    content = (f"title: {json.dumps(title, ensure_ascii=False)}\nid: {rule_id}\nstatus: experimental\n"
        f"description: Generated by Cipher from reviewed case indicators.\nlogsource:\n  category: {logsource}\n"
        f"detection:\n  selection:\n    indicator:\n{quoted}\n  condition: selection\n"
        "falsepositives:\n  - Legitimate infrastructure using the same indicator\nlevel: medium\n")
    return {"format": "sigma", "content": content, "indicatorCount": len(indicators),
            "validation": {"status": "draft", "requiresHumanReview": True}}


def _build_yara(payload: dict[str, Any]) -> dict[str, Any]:
    strings = _string_list(payload.get("strings"), limit=50)
    if not strings: raise HTTPException(status_code=422, detail="至少需要一个样本字符串")
    name = _safe_identifier(str(payload.get("name", "cipher_sample_rule")))
    author = str(payload.get("author", "Cipher Intelligence")).replace('"', "'")[:80]
    declarations = "\n".join(f'    $s{index} = {json.dumps(value, ensure_ascii=False)} ascii wide' for index, value in enumerate(strings, 1))
    threshold = "all of them" if len(strings) <= 2 else f"{max(2, len(strings) // 2)} of them"
    content = (f"rule {name} {{\n  meta:\n    author = \"{author}\"\n    source = \"Cipher reviewed evidence\"\n"
        f"  strings:\n{declarations}\n  condition:\n    {threshold}\n}}\n")
    return {"format": "yara", "content": content, "stringCount": len(strings),
            "validation": {"status": "draft", "requiresHumanReview": True}}


def _cape_to_stix(payload: dict[str, Any]) -> dict[str, Any]:
    report = payload.get("report")
    if not isinstance(report, dict): raise HTTPException(status_code=422, detail="report 必须是对象")
    values: list[str] = []
    for key in ("ips", "domains", "urls", "hashes"):
        raw = report.get(key, [])
        if isinstance(raw, list): values.extend(str(value).strip() for value in raw if str(value).strip())
    sha256 = str(report.get("sha256", "")).strip()
    if sha256: values.append(sha256)
    objects = []
    for value in list(dict.fromkeys(values))[:250]:
        kind = _ioc_type(value)
        pattern_key = {"ip": "ipv4-addr:value", "domain": "domain-name:value", "url": "url:value", "sha256": "file:hashes.SHA-256"}[kind]
        objects.append({"type": "indicator", "spec_version": "2.1",
            "id": f"indicator--{uuid.uuid5(uuid.NAMESPACE_URL, f'cipher:stix:{kind}:{value}')}",
            "pattern_type": "stix", "pattern": f"[{pattern_key} = {json.dumps(value)}]",
            "name": f"CAPE {kind} indicator", "valid_from": datetime.now(timezone.utc).isoformat()})
    bundle = {"type": "bundle", "id": f"bundle--{uuid.uuid4()}", "objects": objects}
    return {"format": "stix-2.1", "bundle": bundle, "objectCount": len(objects),
            "warnings": [] if objects else ["报告中没有可转换的 IOC"]}

def _ioc_type(value: str) -> str:
    import ipaddress
    try: ipaddress.ip_address(value); return "ip"
    except ValueError: pass
    if len(value) == 64 and all(char in "0123456789abcdefABCDEF" for char in value): return "sha256"
    if value.startswith(("http://", "https://")): return "url"
    return "domain"

def _lookup_ioc(value: str, kind: str) -> dict[str, Any]:
    result = {"value": value, "type": kind, "risk": "unknown", "confidence": 20, "sources": [], "raw": {}}
    if settings.virustotal_api_key:
        try:
            if kind == "ip": endpoint = f"https://www.virustotal.com/api/v3/ip_addresses/{value}"
            elif kind == "domain": endpoint = f"https://www.virustotal.com/api/v3/domains/{value}"
            elif kind == "sha256": endpoint = f"https://www.virustotal.com/api/v3/files/{value}"
            else: endpoint = f"https://www.virustotal.com/api/v3/urls/{value}"
            response = httpx.get(endpoint, headers={"x-apikey": settings.virustotal_api_key}, timeout=10)
            if response.is_success:
                stats = response.json().get("data", {}).get("attributes", {}).get("last_analysis_stats", {})
                malicious = int(stats.get("malicious", 0)); suspicious = int(stats.get("suspicious", 0))
                result["risk"] = "critical" if malicious >= 5 else "high" if malicious else "medium" if suspicious else "low"
                result["confidence"] = min(99, 45 + malicious * 8 + suspicious * 4); result["sources"] = ["VirusTotal"]; result["raw"] = {"stats": stats}
        except (httpx.HTTPError, ValueError):
            result["raw"] = {"error": "VirusTotal 查询失败"}
    if settings.misp_url and settings.misp_api_key:
        try:
            response = httpx.post(f"{settings.misp_url.rstrip('/')}/attributes/restSearch", headers={"Authorization": settings.misp_api_key, "Accept": "application/json"}, json={"value": value, "type": kind}, timeout=10)
            if response.is_success:
                attributes = response.json().get("response", {}).get("Attribute", [])
                if attributes:
                    result["sources"].append("MISP"); result["risk"] = "high"; result["confidence"] = max(result["confidence"], 80); result["raw"]["mispMatches"] = len(attributes)
        except (httpx.HTTPError, ValueError):
            result["raw"]["mispError"] = "MISP 查询失败"
    return result


ATTACK_PATTERNS = (
    (("powershell", "command shell", "cmd.exe", "shell command"), "T1059", "Command and Scripting Interpreter", "execution"),
    (("registry run", "run key", "startup folder"), "T1060", "Registry Run Keys / Startup Folder", "persistence"),
    (("scheduled task", "task scheduler"), "T1053", "Scheduled Task/Job", "persistence"),
    (("credential", "lsass", "password dump", "mimikatz"), "T1003", "OS Credential Dumping", "credential-access"),
    (("process discovery", "process list", "tasklist"), "T1057", "Process Discovery", "discovery"),
    (("system information", "systeminfo", "host discovery"), "T1082", "System Information Discovery", "discovery"),
    (("dns", "http", "https", "callback", "command and control", "c2"), "T1071", "Application Layer Protocol", "command-and-control"),
    (("encoded", "obfuscated", "base64", "packing"), "T1027", "Obfuscated/Compressed Files and Information", "defense-evasion"),
    (("inject", "process injection", "remote thread"), "T1055", "Process Injection", "defense-evasion"),
)


def _map_attack(payload: dict[str, Any]) -> dict[str, Any]:
    behaviors = _string_list(payload.get("behaviors"))
    mappings, unmatched = [], []
    seen: set[tuple[str, str]] = set()
    for behavior in behaviors:
        lowered = behavior.casefold()
        matched = False
        for patterns, technique_id, name, tactic in ATTACK_PATTERNS:
            if any(pattern in lowered for pattern in patterns):
                key = (behavior, technique_id)
                if key not in seen:
                    mappings.append({"behavior": behavior, "techniqueId": technique_id, "technique": name,
                                     "tactic": tactic, "confidence": 75, "requiresHumanReview": True})
                    seen.add(key)
                matched = True
        if not matched: unmatched.append(behavior)
    return {"mappings": mappings, "unmatched": unmatched, "mappedCount": len(mappings),
            "coverage": round((len(behaviors) - len(unmatched)) * 100 / len(behaviors)) if behaviors else 0}


def _triage_phishing(payload: dict[str, Any]) -> dict[str, Any]:
    sender = str(payload.get("sender", "")).strip()
    subject = str(payload.get("subject", "")).strip()
    authentication = str(payload.get("authentication", "")).casefold()
    body = str(payload.get("body", "")).casefold()
    urls = _string_list(payload.get("urls", []))
    attachments = _string_list(payload.get("attachments", []))
    score, findings = 0, []
    def add(points: int, code: str, detail: str) -> None:
        nonlocal score
        score += points; findings.append({"code": code, "points": points, "detail": detail})
    if any(value in authentication for value in ("fail", "softfail", "none", "temperror")): add(25, "auth-failure", "SPF/DKIM/DMARC 认证异常")
    if any(word in f"{subject} {body}" for word in ("紧急", "urgent", "立即", "过期", "suspend")): add(15, "urgency", "存在紧迫或威胁性话术")
    if any(word in body for word in ("密码", "password", "验证码", "credential", "login")): add(20, "credential-request", "正文涉及凭据或登录请求")
    if urls: add(min(20, 5 + len(urls) * 3), "external-links", f"包含 {len(urls)} 个链接")
    dangerous = [name for name in attachments if name.casefold().endswith((".exe", ".js", ".vbs", ".scr", ".iso", ".lnk", ".docm", ".xlsm"))]
    if dangerous: add(30, "dangerous-attachment", f"高风险附件：{'、'.join(dangerous[:5])}")
    if sender and "@" not in sender: add(10, "sender-format", "发件人地址格式异常")
    score = min(100, score)
    risk = "critical" if score >= 75 else "high" if score >= 50 else "medium" if score >= 25 else "low"
    actions = ["保留原始邮件与完整邮件头", "对链接与附件进行隔离分析"]
    if score >= 50: actions[:0] = ["隔离邮件并检索其他收件人", "阻断已确认的恶意 IOC"]
    return {"sender": sender, "subject": subject, "score": score, "risk": risk, "findings": findings,
            "recommendedActions": actions, "requiresAnalystReview": True}


def _build_blocklist(payload: dict[str, Any]) -> dict[str, Any]:
    values = list(dict.fromkeys(value.strip().casefold() for value in _string_list(payload.get("indicators"), limit=500)))
    network, excluded = [], []
    for value in values:
        kind = _ioc_type(value)
        (excluded if kind == "sha256" else network).append({"type": kind, "value": value})
    ticket = str(payload.get("ticket", "")).strip()
    expires = max(1, min(8760, int(payload.get("expiresHours", 24) or 24)))
    header = ["# Cipher containment draft", f"# ticket: {ticket or 'not-provided'}", f"# expires-hours: {expires}", "# requires-change-approval: true"]
    content = "\n".join(header + [item["value"] for item in network]) + "\n"
    return {"format": "plain-network-blocklist", "content": content, "entries": network,
            "excluded": excluded, "entryCount": len(network), "expiresHours": expires,
            "validation": {"status": "draft", "requiresHumanReview": True, "rollbackRequired": True}}


def _build_incident_brief(payload: dict[str, Any]) -> dict[str, Any]:
    title = str(payload.get("title", "")).strip()[:255]
    severity = str(payload.get("severity", "unknown")).strip()
    summary = str(payload.get("summary", "")).strip() or "尚无已审核的调查摘要。"
    indicators = _string_list(payload.get("indicators", []), limit=100)
    actions = _string_list(payload.get("actions", []), limit=50)
    executive = f"{title}（{severity}）。{summary} 当前关联 {len(indicators)} 个关键 IOC，已记录 {len(actions)} 项处置动作。"
    markdown = (f"# {title}\n\n## 管理层摘要\n\n{executive}\n\n## 分析师交接\n\n"
                f"- 严重度：{severity}\n- 调查摘要：{summary}\n- 关键 IOC：{'、'.join(indicators) if indicators else '暂无'}\n"
                f"- 已采取动作：{'、'.join(actions) if actions else '尚未记录'}\n\n> 本简报由 Cipher 根据当前 Case 数据生成，签发前需人工复核。\n")
    return {"executiveSummary": executive, "analystBrief": markdown, "indicatorCount": len(indicators),
            "actionCount": len(actions), "requiresHumanReview": True}


def _check_evidence_integrity(payload: dict[str, Any]) -> dict[str, Any]:
    evidence = payload.get("evidence")
    if not isinstance(evidence, list): raise HTTPException(status_code=422, detail="evidence 必须是对象数组")
    blockers, warnings, hashes = [], [], {}
    for index, raw in enumerate(evidence[:500]):
        if not isinstance(raw, dict): blockers.append({"index": index, "code": "invalid-item"}); continue
        label = raw.get("title") or raw.get("id") or index
        if raw.get("reviewStatus") != "verified": blockers.append({"evidence": label, "code": "not-verified"})
        content_hash = str(raw.get("contentHash") or "").strip().casefold()
        if not content_hash: blockers.append({"evidence": label, "code": "missing-hash"})
        else: hashes.setdefault(content_hash, []).append(label)
        if int(raw.get("confidence", 0) or 0) < 50: warnings.append({"evidence": label, "code": "low-confidence"})
        if int(raw.get("sourceTrust", 0) or 0) < 50: warnings.append({"evidence": label, "code": "low-source-trust"})
    duplicates = [{"hash": key, "evidence": values} for key, values in hashes.items() if len(values) > 1]
    warnings.extend({"code": "duplicate-hash", **item} for item in duplicates)
    return {"readyForSigning": bool(evidence) and not blockers, "evidenceCount": len(evidence),
            "blockers": blockers, "warnings": warnings, "duplicateHashes": duplicates}


def _review_capa_capabilities(payload: dict[str, Any]) -> dict[str, Any]:
    capabilities = _string_list(payload.get("capabilities"), limit=300)
    groups = {key: [] for key in ("execution", "persistence", "defense-evasion", "collection", "communication", "other")}
    patterns = {
        "execution": ("execute", "process", "shell", "command", "code"),
        "persistence": ("persist", "registry run", "service", "scheduled task", "startup"),
        "defense-evasion": ("inject", "obfuscat", "pack", "anti-debug", "delete", "disable"),
        "collection": ("capture", "keylog", "screenshot", "clipboard", "credential", "browser"),
        "communication": ("http", "dns", "socket", "download", "upload", "network", "c2"),
    }
    for capability in capabilities:
        lowered = capability.casefold()
        group = next((name for name, words in patterns.items() if any(word in lowered for word in words)), "other")
        groups[group].append(capability)
    high_signal = sum(len(groups[name]) for name in ("persistence", "defense-evasion", "collection", "communication"))
    risk = "high" if high_signal >= 4 else "medium" if high_signal else "low"
    checklist = ["在 CAPE 进程树中验证能力是否真实触发", "将高信号能力与原始样本哈希关联", "排除库代码和未达路径导致的静态误报"]
    return {"upstream": "mandiant/capa@v9.4.0", "risk": risk, "groups": groups,
            "capabilityCount": len(capabilities), "highSignalCount": high_signal,
            "reviewChecklist": checklist, "requiresHumanReview": True}


LOLBAS_BINARIES = {
    "certutil": ("download-or-decode", "检查 URL、-cache/-decode 参数与落地文件"),
    "mshta": ("script-execution", "检查远程 HTA/JavaScript 与父进程"),
    "rundll32": ("dll-execution", "检查 DLL 路径、导出函数与网络连接"),
    "regsvr32": ("scriptlet-execution", "检查 /i 与 scrobj.dll 参数"),
    "bitsadmin": ("background-transfer", "检查 BITS 作业、远程 URL 和落地路径"),
    "wmic": ("remote-or-process-execution", "检查 process call create 与远程节点"),
    "powershell": ("script-execution", "检查 -enc、IEX、下载函数和 ScriptBlock 日志"),
}


def _analyze_lolbas(payload: dict[str, Any]) -> dict[str, Any]:
    commands = _string_list(payload.get("commands"), limit=300)
    matches = []
    for command in commands:
        lowered = command.casefold()
        for binary, (function, pivot) in LOLBAS_BINARIES.items():
            if re.search(rf"(?:^|[\\/\s]){re.escape(binary)}(?:\.exe)?(?:\s|$)", lowered):
                suspicious = any(token in lowered for token in ("http://", "https://", "-enc", "/i:", "scrobj", "process call create", "-decode"))
                matches.append({"binary": binary, "function": function, "command": command,
                                "severity": "high" if suspicious else "medium", "investigationPivot": pivot})
    return {"upstream": "LOLBAS-Project/LOLBAS@3403b338875b", "matches": matches,
            "matchCount": len(matches), "unmatchedCount": max(0, len(commands) - len({m['command'] for m in matches})),
            "disclaimer": "匹配仅表示原生工具具有可滥用能力，必须结合父进程、用户和网络证据复核。"}


GTFO_BINARIES = {
    "bash": ("shell",), "sh": ("shell",), "find": ("shell", "file-read"),
    "vim": ("shell", "file-read", "file-write"), "less": ("shell", "file-read"),
    "awk": ("shell", "file-read"), "python": ("shell",), "python3": ("shell",),
    "perl": ("shell",), "tar": ("shell", "file-read"), "cp": ("file-write",),
    "curl": ("download", "upload"), "wget": ("download",), "openssl": ("file-read", "network"),
}


def _analyze_gtfobins(payload: dict[str, Any]) -> dict[str, Any]:
    commands = _string_list(payload.get("commands"), limit=300)
    matches = []
    for command in commands:
        tokens = re.findall(r"[A-Za-z0-9_.+-]+", command.casefold())
        binary = next((token for token in tokens if token in GTFO_BINARIES), None)
        if binary:
            elevated = bool(re.search(r"(?:^|\s)sudo\s", command)) or "suid" in command.casefold()
            matches.append({"binary": binary, "capabilities": list(GTFO_BINARIES[binary]), "command": command,
                            "elevatedContext": elevated, "severity": "high" if elevated else "medium",
                            "investigationPivots": ["sudo 日志", "父进程与 TTY", "执行用户与文件权限"]})
    return {"upstream": "GTFOBins/GTFOBins.github.io@acd524623f9c", "matches": matches,
            "matchCount": len(matches), "requiresHumanReview": True}


def _plan_nuclei(payload: dict[str, Any]) -> dict[str, Any]:
    if payload.get("authorizationConfirmed") is not True:
        raise HTTPException(status_code=422, detail="必须确认已获得所有目标资产的测试授权")
    assets = _string_list(payload.get("assets"), limit=100)
    if not assets: raise HTTPException(status_code=422, detail="至少需要一个已授权资产")
    severities = _string_list(payload.get("severities", ["critical", "high"]), limit=5)
    allowed = {"info", "low", "medium", "high", "critical"}
    severities = [value.casefold() for value in severities if value.casefold() in allowed] or ["critical", "high"]
    tags = _string_list(payload.get("tags", []), limit=20)
    rate = max(1, min(50, int(payload.get("rateLimit", 10) or 10)))
    args = ["nuclei", "-l", "authorized-targets.txt", "-severity", ",".join(severities), "-rl", str(rate), "-c", "5", "-jsonl", "-o", "cipher-nuclei-results.jsonl"]
    if tags: args.extend(["-tags", ",".join(tags)])
    return {"upstream": "projectdiscovery/nuclei-templates@v10.4.7", "authorizedAssets": assets,
            "targetFile": "\n".join(assets) + "\n", "commandPreview": " ".join(args),
            "controls": {"rateLimit": rate, "concurrency": 5, "executesScan": False,
                         "requiresChangeApproval": True, "retainJsonlEvidence": True},
            "severities": severities, "tags": tags}

def _review_external_payload(payload: dict[str, Any], key: str) -> dict[str, Any]:
    """Keep curated GitHub adapters deterministic until a native tool is configured."""
    raw = payload.get("findings") or payload.get("results") or payload.get("rule") or payload.get("objectives")
    count = len(raw) if isinstance(raw, (list, dict)) else 0
    return {"adapter": key, "itemCount": count, "summary": "已完成结构化预审，等待接入经授权的上游工具。",
            "requiresHumanReview": True, "execution": {"performed": False, "reason": "dry-run adapter"}}

def execute_skill(db: Session, skill: SkillPackage, user_id: int, payload: dict[str, Any], policy: dict[str, Any] | None = None) -> SkillRun:
    manifest = json.loads(skill.manifest_json or "{}")
    required = manifest.get("inputs", {}).get("required", []) if isinstance(manifest.get("inputs"), dict) else []
    missing = [str(key) for key in required if key not in payload]
    if missing:
        raise HTTPException(status_code=422, detail={"message": "Skill 输入不完整", "missing": missing})
    run_case_id = payload.get("caseId")
    if run_case_id is not None:
        try:
            normalized_case_id = int(run_case_id)
        except (TypeError, ValueError) as error:
            raise HTTPException(status_code=422, detail="caseId 必须是有效整数") from error
        owned_case = db.scalar(select(InvestigationCase).where(
            InvestigationCase.id == normalized_case_id,
            InvestigationCase.owner_user_id == user_id,
        ))
        if owned_case is None:
            raise HTTPException(status_code=404, detail="Case not found")
        payload = {**payload, "caseId": normalized_case_id}
    tools = json.loads(skill.permissions_json or "[]")
    output: dict[str, Any] = {
        "skill": {"key": skill.skill_key, "version": skill.version},
        "summary": "Skill 已完成输入校验，等待已授权工具或模型适配器执行。",
        "input": payload,
        "evidence": [],
        "nextActions": [],
    }
    if skill.skill_key == "ioc-enrichment":
        values = payload.get("iocs", payload.get("ioc", [])); values = values if isinstance(values, list) else [values]
        output["iocs"] = [_lookup_ioc(str(value.get("value", "")), str(value.get("type") or _ioc_type(str(value.get("value", ""))))) if isinstance(value, dict) else _lookup_ioc(str(value), _ioc_type(str(value))) for value in values if str(value.get("value", "") if isinstance(value, dict) else value).strip()]
        output["summary"] = f"已富化 {len(output['iocs'])} 项 IOC。"
        if run_case_id := payload.get("caseId"):
            for item in output["iocs"]:
                normalized = item["value"].strip().casefold()
                existing = db.scalar(select(CaseIndicator).where(CaseIndicator.case_id == int(run_case_id), CaseIndicator.indicator_type == item["type"], CaseIndicator.normalized_value == normalized))
                if existing:
                    existing.risk_level, existing.confidence, existing.enrichment_json, existing.source_type, existing.last_seen_at = item["risk"], item["confidence"], json.dumps(item, ensure_ascii=False), "skill", datetime.now(timezone.utc)
                else:
                    db.add(CaseIndicator(case_id=int(run_case_id), indicator_type=item["type"], value=item["value"], normalized_value=normalized, risk_level=item["risk"], confidence=item["confidence"], source_type="skill", enrichment_json=json.dumps(item, ensure_ascii=False)))
            db.add(CaseEvent(case_id=int(run_case_id), event_type="skill_completed", title="IOC Skill 已完成", detail=f"已富化 {len(output['iocs'])} 项 IOC", metadata_json=json.dumps({"skill": skill.skill_key, "count": len(output["iocs"])}, ensure_ascii=False), actor=str(user_id)))
    elif skill.skill_key == "sigma-rule-builder":
        output.update(_build_sigma(payload)); output["summary"] = "Sigma 草案已生成，部署前必须验证字段映射与误报。"
    elif skill.skill_key == "yara-rule-builder":
        output.update(_build_yara(payload)); output["summary"] = "YARA 草案已生成，部署前必须使用良性与恶意样本测试。"
    elif skill.skill_key == "cape-to-stix":
        output.update(_cape_to_stix(payload)); output["summary"] = f"已生成包含 {output['objectCount']} 个 Indicator 的 STIX 2.1 Bundle。"
    elif skill.skill_key == "attack-technique-mapper":
        output.update(_map_attack(payload)); output["summary"] = f"已生成 {output['mappedCount']} 条 ATT&CK 候选映射。"
    elif skill.skill_key == "phishing-triage":
        output.update(_triage_phishing(payload)); output["summary"] = f"钓鱼分诊完成，风险 {output['risk']}，评分 {output['score']}。"
    elif skill.skill_key == "firewall-blocklist-builder":
        output.update(_build_blocklist(payload)); output["summary"] = f"已生成 {output['entryCount']} 条网络封禁条目草案。"
    elif skill.skill_key == "incident-brief-builder":
        output.update(_build_incident_brief(payload)); output["summary"] = "事件简报已生成，签发前需人工复核。"
    elif skill.skill_key == "evidence-integrity-checker":
        output.update(_check_evidence_integrity(payload)); output["summary"] = "证据已就绪，可进入签名流程。" if output["readyForSigning"] else f"证据存在 {len(output['blockers'])} 项阻断问题。"
    elif skill.skill_key == "capa-capability-review":
        output.update(_review_capa_capabilities(payload)); output["summary"] = f"已复核 {output['capabilityCount']} 项 capa 能力，风险 {output['risk']}。"
    elif skill.skill_key == "lolbas-command-analyzer":
        output.update(_analyze_lolbas(payload)); output["summary"] = f"识别 {output['matchCount']} 条 LOLBAS 候选命令。"
    elif skill.skill_key == "gtfobins-command-analyzer":
        output.update(_analyze_gtfobins(payload)); output["summary"] = f"识别 {output['matchCount']} 条 GTFOBins 候选命令。"
    elif skill.skill_key == "nuclei-template-planner":
        output.update(_plan_nuclei(payload)); output["summary"] = f"已为 {len(output['authorizedAssets'])} 个授权资产生成限速验证计划，未执行扫描。"
    elif skill.skill_key in {"trivy-vulnerability-triage", "semgrep-rule-reviewer", "velociraptor-hunt-planner", "checkov-iac-review"}:
        output.update(_review_external_payload(payload, skill.skill_key)); output["summary"] = "GitHub 生态 Skill 预审完成，结果需人工复核。"
    policy = policy or {}
    serialized_output = json.dumps(output, ensure_ascii=False)
    max_output = int(policy.get("maxOutputBytes", 262_144))
    truncated = len(serialized_output.encode()) > max_output
    if truncated:
        output = {"skill": output["skill"], "summary": "Skill 输出超过安全上限，内容已截断。",
                  "truncatedPreview": serialized_output.encode()[:max_output].decode("utf-8", errors="ignore")}
    run = SkillRun(skill_id=skill.id, user_id=user_id, case_id=payload.get("caseId"), status="completed",
        input_json=json.dumps(payload, ensure_ascii=False), output_json=json.dumps(output, ensure_ascii=False),
        tool_allowlist_json=json.dumps(tools, ensure_ascii=False), policy_json=json.dumps(policy),
        attempt_count=1, output_truncated=truncated, completed_at=datetime.now(timezone.utc))
    db.add(run); db.commit(); db.refresh(run)
    return run

def serialize_run(run: SkillRun) -> dict[str, Any]:
    return {"id": run.id, "skillId": run.skill_id, "caseId": run.case_id, "status": run.status,
            "input": json.loads(run.input_json or "{}"), "output": json.loads(run.output_json or "{}"),
            "tools": json.loads(run.tool_allowlist_json or "[]"), "policy": json.loads(run.policy_json or "{}"),
            "attemptCount": run.attempt_count, "outputTruncated": run.output_truncated, "error": run.error_message,
            "createdAt": run.created_at, "completedAt": run.completed_at}
